apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8s-job-autotest-sample
build:
  artifacts:
    - image: localhost:5000/hello-world-timer
      context: .
      docker:
        dockerfile: apps/Dockerfile
  local:
    useBuildkit: true
    push: true
deploy:
  helm:
    releases:
      - name: hello-world-timer-job
        chartPath: apps/helm
        setValueTemplates:
          image.pullPolicy: "{{ .IMAGE_PULL_POLICY }}"
        setValues:
          image.PullPolicy: "IfNotPresent"

profiles:
- name: prod
  deploy:
    helm:
      releases:
        - name: hello-world-timer-job
          chartPath: apps/helm
            # setValueTemplates:
            #   image.pullPolicy: "{{ .IMAGE_PULL_POLICY }}"
            # setValues:
            #   image.PullPolicy: "Always"
