apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: k8s-job-autotest-sample
build:
  artifacts:
    - image: hello-world-timer
      context: .
      docker:
        dockerfile: apps/Dockerfile
  local:
    useBuildkit: true

profiles:
- name: dev
  deploy:
    helm:
      releases:
        - name: hello-world-timer-job
          chartPath: charts/hello-world-timer-job
          setValueTemplates:
            image.pullPolicy: "{{ .IMAGE_PULL_POLICY }}"
          setValues:
            image.PullPolicy: "IfNotPresent"
- name: prod
  deploy:
    helm:
      releases:
        - name: hello-world-timer-job
          chartPath: charts/hello-world-timer-job
          setValueTemplates:
            image.pullPolicy: "{{ .IMAGE_PULL_POLICY }}"
          setValues:
            image.PullPolicy: "IfNotPresent"
            # image.PullPolicy: "Always" // set Always here when remote repository is available
