apiVersion: batch/v1
kind: Job
metadata:
  name: hello-world-timer-job
spec:
  template:
    spec:
      containers:
        - name: hello-world-timer
          image: localhost:5000/hello-world-timer
          imagePullPolicy: {{ .Values.image.pullPolicy }}
      restartPolicy: Never
